dist: xenial
sudo: false
latex: false

language: r

r: 
  - release

r_packages:
  - rsconnect
  - shiny

apt_packages:
  - libgdal-dev
  - libudunits2-dev

warnings_are_errors: false

cache:
  packages: true

script:
  - R -f deploy.R